query DiseaseAssociationsQuery(
  $id: String!
  $index: Int!
  $size: Int!
  $sortBy: String!
  $datasourcePolicyOverrides: [DatasourcePolicyOverride!]!
  $rowsFilter: [String!]
  $facetFilters: [String!]
  $entitySearch: String!
) {
  disease(efoId: $id) {
    id
    name
    associatedTargets(
      page: { index: $index, size: $size }
      sort: { key: $sortBy, direction: DESCENDING }
      datasourcePolicyOverrides: $datasourcePolicyOverrides
      Bs: $rowsFilter
      facetFilters: $facetFilters
      BFilter: $entitySearch
    ) {
      count
      rows {
        novelty
        target {
          id
          approvedSymbol
          approvedName
        }
        score
        datasourceScores {
          componentId: id
          score
        }
      }
    }
  }
}
