import { useEffect, useReducer, useMemo, useCallback } from "react";
import { gql, useQuery } from "@apollo/client";
import { Alert, Box, Grid, Typography, Tabs, Tab } from "@mui/material";
import { makeStyles } from "@mui/styles";
import { Link, OtInvalidResultFilters } from "ui";
import { getConfig } from "@ot/config";
import { v1 } from "uuid";
import DownloadsCard from "./DownloadsCard";
import DownloadsFilter from "./DownloadsFilter";
import DownloadsLoading from "./DownloadsLoading";
import { createInitialState, downloadsReducer, initialState } from "./context/downloadsReducer";
import { setDownloadsData, setError, setLoading } from "./context/downloadsActions";
import { DownloadsContext } from "./context/DownloadsContext";
import DownloadsTags from "./DownloadsTags";
import { Route, Routes, useSearchParams } from "react-router-dom";
import DownloadsDialog from "./DownloadsDialog";
import { GraphVisualization, transformRecordSetToGraph } from "./graph";

const config = getConfig();

const useStyles = makeStyles(theme => ({
  alert: {
    marginBottom: theme.spacing(2),
  },
}));

// QUERY
const DOWNLOADS_QUERY = gql`
  query DownloadsQuery {
    meta {
      downloads
    }
  }
`;

function DownloadsPage() {
  const { data, loading, error } = useQuery(DOWNLOADS_QUERY);
  const [state, dispatch] = useReducer(downloadsReducer, initialState, createInitialState);
  const classes = useStyles();

  // View mode lives in the URL so it (and the selected graph node, set
  // below) survive a refresh and can be linked to directly from a card.
  const [searchParams, setSearchParams] = useSearchParams();
  const viewMode = searchParams.get("view") === "graph" ? "graph" : "cards";

  const handleViewModeChange = (e, newValue) => {
    setSearchParams(prev => {
      const next = new URLSearchParams(prev);
      next.set("view", newValue);
      next.delete("node");
      return next;
    });
  };

  const handleViewConnections = useCallback(
    id => {
      setSearchParams(prev => {
        const next = new URLSearchParams(prev);
        next.set("view", "graph");
        next.set("node", id);
        return next;
      });
    },
    [setSearchParams]
  );

  // Connection count per dataset (RecordSet id), for the "N connections"
  // link on each card that jumps to the graph view with that node highlighted.
  const degreeById = useMemo(() => {
    const recordSets = (state.schemaRows || []).filter(rs => rs["@type"] === "cr:RecordSet");
    const { nodes } = transformRecordSetToGraph(recordSets);
    return new Map(nodes.map(n => [n.data.id, n.data.degree || 0]));
  }, [state.schemaRows]);

  useEffect(() => {
    if (loading) {
      dispatch(setLoading(true));
    } else if (error) {
      dispatch(setError(error));
    } else if (data?.meta?.downloads) {
      dispatch(setDownloadsData(JSON.parse(data.meta.downloads)));
    }
  }, [data, loading, error]);

  if (state.loading) return <DownloadsLoading />;

  return (
    <DownloadsContext.Provider value={{ state, dispatch }}>
      <>
        <Typography variant="h4" component="h1" paragraph>
          {state.downloadsData?.name}
        </Typography>
        <Typography paragraph>{state.downloadsData?.description}</Typography>

        {config.profile.isPartnerPreview ? (
          <Alert severity="info" className={classes.alert}>
            This table provides data file paths that have been integrated into the Open Targets
            Partner Preview Platform. This includes pre-publication data generated by the consortium
            combined with{" "}
            <Link
              external
              to="https://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/output/"
            >
              {" "}
              publicly available datasets
            </Link>
            . Please contact{" "}
            <Link to={`mailto: ${config.profile.helpdeskEmail}`} external>
              {config.profile.helpdeskEmail}
            </Link>{" "}
            to access the following datasets.
          </Alert>
        ) : null}

        <DownloadsTags />

        {/* View mode tabs */}
        <Box sx={{ borderBottom: 1, borderColor: "divider", mb: 2 }}>
          <Tabs value={viewMode} onChange={handleViewModeChange}>
            <Tab label="Card View" value="cards" />
            <Tab label="Graph View" value="graph" />
          </Tabs>
        </Box>

        {/* Card view */}
        {viewMode === "cards" && (
          <Grid container sx={{ display: "flex", justifyContent: "space-between" }}>
            <Grid item xs={12} md={3} lg={2} sx={{ display: "flex", justifyContent: "center" }}>
              <DownloadsFilter />
            </Grid>
            <Grid
              item
              xs={12}
              md={9}
              lg={10}
              sx={{ display: "flex", flexDirection: "column", gap: 1, pl: { md: 2 } }}
            >
              <Typography variant="h6" sx={{ fontWeight: "bold", mb: 2 }}>
                All Datasets ({state.count})
              </Typography>
              <Box
                sx={{
                  display: "flex",
                  flexWrap: "wrap",
                  justifyContent: "center",
                  gap: 2,
                }}
              >
                {state.count > 0 ? (
                  <>
                    {state.filteredRows.map(e => (
                      <DownloadsCard
                        key={v1()}
                        data={e}
                        connections={degreeById.get(String(e["@id"]).replace("-fileset", ""))}
                        onViewConnections={handleViewConnections}
                      />
                    ))}
                  </>
                ) : (
                  <OtInvalidResultFilters />
                )}
              </Box>
            </Grid>
          </Grid>
        )}

        {/* Graph view */}
        {viewMode === "graph" && (
          <Box sx={{ mb: 2 }}>
            <GraphVisualization />
          </Box>
        )}
      </>
      <Routes>
        <Route path="/:downloadsRow/:downloadsView" element={<DownloadsDialog />} />
      </Routes>
    </DownloadsContext.Provider>
  );
}

export default DownloadsPage;
